package com.minseo.piyakbank.core

/** IDs, names and prices match the iOS CatalogSeed; no billing products. */
object Catalog {
    val items: List<CatalogItem> = listOf(
        CatalogItem("bg.cozy_cream", DecorSlot.bg, "포근한 크림", 0, true),
        CatalogItem("floorProp.plant", DecorSlot.floorProp, "화분", 0, true),
        CatalogItem("rug.oval_coral", DecorSlot.rug, "코랄 러그", 0, true),
        CatalogItem("bodyFront.hoodie_mint", DecorSlot.bodyFront, "민트 후드티", 0, true),
        CatalogItem("bodyFront.graduation_gown", DecorSlot.bodyFront, "졸업 가운", 2000, false),
        CatalogItem("bg.night_sky", DecorSlot.bg, "밤하늘", 1250, false),
        CatalogItem("wallDeco.clock", DecorSlot.wallDeco, "벽시계", 450, false),
        CatalogItem("bigFurniture.bookshelf", DecorSlot.bigFurniture, "책장", 2250, false),
        CatalogItem("bg.sky_blue", DecorSlot.bg, "맑은 하늘", 900, false),
        CatalogItem("bg.sakura_pink", DecorSlot.bg, "벚꽃", 1100, false),
        CatalogItem("rug.round_stripe", DecorSlot.rug, "줄무늬 러그", 600, false),
        CatalogItem("rug.cloud", DecorSlot.rug, "구름 러그", 800, false),
        CatalogItem("rug.star", DecorSlot.rug, "별 러그", 800, false),
        CatalogItem("floorProp.lamp", DecorSlot.floorProp, "스탠드 조명", 700, false),
        CatalogItem("floorProp.books", DecorSlot.floorProp, "책 더미", 500, false),
        CatalogItem("floorProp.puppy", DecorSlot.floorProp, "강아지 인형", 1000, false),
        CatalogItem("wallDeco.frame", DecorSlot.wallDeco, "액자", 550, false),
        CatalogItem("wallDeco.mirror", DecorSlot.wallDeco, "거울", 650, false),
        CatalogItem("bigFurniture.nightstand", DecorSlot.bigFurniture, "협탁", 2000, false),
        CatalogItem("bigFurniture.shelf", DecorSlot.bigFurniture, "벽 선반", 1900, false),
        CatalogItem("headTop.straw_hat", DecorSlot.headTop, "밀짚모자", 600, false),
        CatalogItem("eyes.round_glasses", DecorSlot.eyes, "둥근안경", 750, false),
        CatalogItem("neck.scarf_coral", DecorSlot.neck, "포근 목도리", 500, false),
        CatalogItem("bg.mint_garden", DecorSlot.bg, "민트 가든", 1000, false),
        CatalogItem("bg.lavender", DecorSlot.bg, "라벤더", 1100, false),
        CatalogItem("bg.sunset", DecorSlot.bg, "노을", 1200, false),
        CatalogItem("bg.ocean", DecorSlot.bg, "바다", 1200, false),
        CatalogItem("bg.forest", DecorSlot.bg, "숲속", 1300, false),
        CatalogItem("wallDeco.garland", DecorSlot.wallDeco, "가랜드", 450, false),
        CatalogItem("wallDeco.poster", DecorSlot.wallDeco, "삐약 포스터", 500, false),
        CatalogItem("wallDeco.window", DecorSlot.wallDeco, "창문", 650, false),
        CatalogItem("wallDeco.hanging_plant", DecorSlot.wallDeco, "행잉플랜트", 600, false),
        CatalogItem("wallDeco.photo_frames", DecorSlot.wallDeco, "사진 액자", 550, false),
        CatalogItem("wallDeco.moon_lamp", DecorSlot.wallDeco, "달 조명", 700, false),
        CatalogItem("bigFurniture.sofa", DecorSlot.bigFurniture, "소파", 2100, false),
        CatalogItem("bigFurniture.wardrobe", DecorSlot.bigFurniture, "옷장", 2200, false),
        CatalogItem("bigFurniture.piano", DecorSlot.bigFurniture, "피아노", 4000, false),
        CatalogItem("bigFurniture.desk", DecorSlot.bigFurniture, "책상", 2000, false),
        CatalogItem("bigFurniture.fridge", DecorSlot.bigFurniture, "냉장고", 2400, false),
        CatalogItem("bigFurniture.tv", DecorSlot.bigFurniture, "TV", 3000, false),
        CatalogItem("floorProp.moon_jar", DecorSlot.floorProp, "달항아리", 900, false),
        CatalogItem("floorProp.cactus", DecorSlot.floorProp, "선인장", 600, false),
        CatalogItem("floorProp.balloons", DecorSlot.floorProp, "풍선", 700, false),
        CatalogItem("floorProp.toybox", DecorSlot.floorProp, "장난감 상자", 800, false),
        CatalogItem("floorProp.coin_pile", DecorSlot.floorProp, "동전 더미", 1100, false),
        CatalogItem("rug.checker", DecorSlot.rug, "체크 러그", 650, false),
        CatalogItem("rug.heart", DecorSlot.rug, "하트 러그", 750, false),
        CatalogItem("rug.rainbow", DecorSlot.rug, "무지개 러그", 850, false),
        CatalogItem("rug.leaf", DecorSlot.rug, "잎사귀 러그", 700, false),
        CatalogItem("rug.donut", DecorSlot.rug, "도넛 러그", 800, false),
        CatalogItem("bodyFront.stripe_tee", DecorSlot.bodyFront, "줄무늬 티", 750, false),
        CatalogItem("bodyFront.overalls", DecorSlot.bodyFront, "멜빵바지", 900, false),
        CatalogItem("bodyFront.sweater", DecorSlot.bodyFront, "니트 스웨터", 850, false),
        CatalogItem("bodyFront.raincoat", DecorSlot.bodyFront, "비옷", 950, false),
        CatalogItem("bodyFront.suit_vest", DecorSlot.bodyFront, "정장 조끼", 1250, false),
        CatalogItem("bodyFront.pajama", DecorSlot.bodyFront, "잠옷", 800, false),
        CatalogItem("bodyFront.padding_vest", DecorSlot.bodyFront, "패딩 조끼", 1100, false),
        CatalogItem("headTop.beret", DecorSlot.headTop, "베레모", 600, false),
        CatalogItem("headTop.party_cone", DecorSlot.headTop, "파티 고깔", 450, false),
        CatalogItem("headTop.crown", DecorSlot.headTop, "왕관", 1500, false),
        CatalogItem("headTop.beanie", DecorSlot.headTop, "비니", 650, false),
        CatalogItem("headTop.cap", DecorSlot.headTop, "캡모자", 700, false),
        CatalogItem("headTop.wizard_hat", DecorSlot.headTop, "마법사 모자", 1000, false),
        CatalogItem("headTop.flower", DecorSlot.headTop, "꽃 장식", 500, false),
        CatalogItem("headTop.chef_hat", DecorSlot.headTop, "요리사 모자", 750, false),
        CatalogItem("eyes.sunglasses", DecorSlot.eyes, "선글라스", 800, false),
        CatalogItem("eyes.heart_glasses", DecorSlot.eyes, "하트 안경", 750, false),
        CatalogItem("eyes.star_glasses", DecorSlot.eyes, "별 안경", 750, false),
        CatalogItem("eyes.monocle", DecorSlot.eyes, "외알 안경", 900, false),
        CatalogItem("eyes.goggles", DecorSlot.eyes, "고글", 850, false),
        CatalogItem("eyes.eyepatch", DecorSlot.eyes, "안대", 700, false),
        CatalogItem("eyes.glasses_red", DecorSlot.eyes, "빨간 뿔테", 650, false),
        CatalogItem("eyes.glasses_blue", DecorSlot.eyes, "파란 뿔테", 650, false),
        CatalogItem("neck.ribbon", DecorSlot.neck, "리본", 500, false),
        CatalogItem("neck.bowtie", DecorSlot.neck, "나비넥타이", 600, false),
        CatalogItem("neck.gold_chain", DecorSlot.neck, "골드 체인", 1400, false),
        CatalogItem("neck.scarf_mint", DecorSlot.neck, "민트 목도리", 550, false),
        CatalogItem("neck.pearl", DecorSlot.neck, "진주 목걸이", 1200, false),
        CatalogItem("neck.bandana", DecorSlot.neck, "반다나", 500, false),
        CatalogItem("neck.bell", DecorSlot.neck, "방울", 450, false),
        CatalogItem("neck.tie", DecorSlot.neck, "넥타이", 650, false),
    )
    private val byId = items.associateBy { it.id }
    fun find(id: String): CatalogItem? = byId[id]
}
